package ch.lueem.tradingbot.adapters.execution.binance.model;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

import ch.lueem.tradingbot.core.strategy.action.TradeAction;

/** Describes one actual trade generated by a Binance order. */
public record BinanceFill(
        long tradeId,
        long orderId,
        String symbol,
        TradeAction action,
        BigDecimal price,
        BigDecimal quantity,
        BigDecimal quoteQuantity,
        BigDecimal commission,
        String commissionAsset,
        OffsetDateTime executedAt) {
}
